Repository the-dr-lazy/cascade, pull requests merged in 2021-02, with the labels that each got.

#25 Upgrade stackage snapshot to LTS 16.31
  cabal.project.freeze
Labels: Priority: Critical, Status: Completed, Type: Maintenance

#26 Redistribute state machine tests into separate modules
  cascade-api/test/Test/Cascade/Api/StateMachine.hs
  cascade-api/test/Test/Cascade/Api/StateMachine/Command/Project.hs
  cascade-api/test/Test/Cascade/Api/StateMachine/Model.hs
Labels: Priority: Medium, Scope: cascade-api, Status: Completed, Type: Maintenance

#27 Add pre-commit Git hook
  .githooks/pre-commit
Labels: Priority: Medium, Status: Completed, Type: Maintenance

#17 User and authentication
  .github/workflows/ci.yml
  cabal.project.freeze
  cascade-api/Setup.hs
  cascade-api/cascade-api.cabal
  cascade-api/src/Cascade/Api.hs
  cascade-api/src/Cascade/Api/Data/Authentication.hs
  cascade-api/src/Cascade/Api/Data/ByteString/Password.hs
  cascade-api/src/Cascade/Api/Data/Id.hs
  cascade-api/src/Cascade/Api/Data/Jwt.hs
  cascade-api/src/Cascade/Api/Data/Prelude.hs
  cascade-api/src/Cascade/Api/Data/Session.hs
  cascade-api/src/Cascade/Api/Data/Text/EmailAddress.hs
  cascade-api/src/Cascade/Api/Data/Text/Username.hs
  cascade-api/src/Cascade/Api/Data/User.hs
  cascade-api/src/Cascade/Api/Database.hs
  cascade-api/src/Cascade/Api/Database/User.hs
  cascade-api/src/Cascade/Api/Effect/Database/User.hs
  cascade-api/src/Cascade/Api/Effect/Scrypt.hs
  cascade-api/src/Cascade/Api/Network/Anatomy/Api.hs
  cascade-api/src/Cascade/Api/Network/Anatomy/Api/Authentication.hs
  cascade-api/src/Cascade/Api/Network/Anatomy/Api/Users.hs
  cascade-api/src/Cascade/Api/Network/Anatomy/Prelude.hs
  cascade-api/src/Cascade/Api/Network/Server.hs
  cascade-api/src/Cascade/Api/Network/Server/Api.hs
  cascade-api/src/Cascade/Api/Network/Server/Api/Authentication.hs
  cascade-api/src/Cascade/Api/Network/Server/Api/Users.hs
  cascade-api/src/Cascade/Api/Network/Wai/Application.hs
  cascade-api/src/Cascade/Api/Orphans.hs
  cascade-api/src/Cascade/Api/Servant/Authentication.hs
  cascade-api/src/Cascade/Api/Servant/Response.hs
  cascade-api/test/Cascade/Api/Hedgehog/Gen/Prelude.hs
  cascade-api/test/Cascade/Api/Hedgehog/Gen/Text.hs
  cascade-api/test/Cascade/Api/Network/TestClient/Api.hs
  cascade-api/test/Cascade/Api/Network/TestClient/Api/Users.hs
  cascade-api/test/Test/Cascade/Api/StateMachine.hs
  cascade-api/test/Test/Cascade/Api/StateMachine/Command/Project.hs
  cascade-api/test/Test/Cascade/Api/StateMachine/Command/User.hs
  cascade-api/test/Test/Cascade/Api/StateMachine/Model.hs
  cascade-prelude/cascade-prelude.cabal
  cascade-prelude/src/Cascade/Data/ByteString.hs
  cascade-prelude/src/Cascade/Data/Char.hs
  cascade-prelude/test/Main.hs
  migrations/deploy/set_updated_at.sql
  migrations/deploy/users.sql
  migrations/deploy/users_before_update_trigger.sql
  migrations/revert/set_updated_at.sql
  migrations/revert/users.sql
  migrations/revert/users_before_update_trigger.sql
  migrations/sqitch.plan
  migrations/verify/set_updated_at.sql
  migrations/verify/users.sql
  migrations/verify/users_before_update_trigger.sql
  scripts/ci/test
  scripts/codecov
Labels: Priority: Low, Scope: cascade-api, Status: Review Needed, Type: Enhancement

#31 Add setup script to Makefile
  Makefile
Labels: Priority: Critical, Status: Review Needed, Type: Maintenance

#35 Disable ubuntu-latest builds
  .github/workflows/ci.yml
Labels: Priority: Critical, Status: Completed, Type: Maintenance
